name: firebase_multi_vendor_project
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  # google_fonts: ^4.0.4
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.2.1
  flutter_easyloading: ^3.0.5
  image_picker: ^0.8.7+5
  shared_preferences: ^2.1.1
  connectivity_plus: ^4.0.1
  uuid: ^3.0.7
  cached_network_image: ^3.2.3
  url_launcher: ^6.0.3
  provider: ^6.0.5
  flutter_localization:
  intl: ^0.17.0
  flutter_screenutil: ^5.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/user_placeholder_image.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RobotoMono
      fonts:
        # - asset: assets/fonts/RobotoMono-Bold.ttf
        # - asset: assets/fonts/RobotoMono-Italic.ttf
        # - asset: assets/fonts/RobotoMono-Medium.ttf
        - asset: assets/fonts/RobotoMono-Regular.ttf
        # - asset: assets/fonts/RobotoMono-SemiBold.ttf
        # - asset: assets/fonts/RobotoMono-Thin.ttf
          # style: italic

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
